export const Data = [
  { make: 'Tesla', model: 'Model Y', price: 64950, electric: true },
  { make: 'Ford', model: 'F-Series', price: 33850, electric: false },
  { make: 'Toyota', model: 'Corolla', price: 29600, electric: false },
  { make: 'Honda', model: 'Civic', price: 28500, electric: false },
  { make: 'Chevrolet', model: 'Silverado', price: 37500, electric: false },
  { make: 'BMW', model: '3 Series', price: 49500, electric: false },
  { make: 'Mercedes-Benz', model: 'C-Class', price: 52500, electric: false },
  { make: 'Audi', model: 'A4', price: 47500, electric: false },
  { make: 'Nissan', model: 'Altima', price: 26500, electric: false },
  { make: 'Hyundai', model: 'Elantra', price: 23500, electric: false },
  { make: 'Volkswagen', model: 'Jetta', price: 25500, electric: false },
  { make: 'Subaru', model: 'Outback', price: 32500, electric: false },
  { make: 'Mazda', model: 'CX-5', price: 31500, electric: false },
  { make: 'Kia', model: 'Sportage', price: 29500, electric: false },
  { make: 'Jeep', model: 'Wrangler', price: 38500, electric: false },
  { make: 'Tesla', model: 'Model 3', price: 49500, electric: true },
  { make: 'Lexus', model: 'ES', price: 45500, electric: false },
  { make: 'Infiniti', model: 'Q50', price: 43500, electric: false },
  { make: 'Acura', model: 'TLX', price: 41500, electric: false },
  { make: 'Cadillac', model: 'CT5', price: 44500, electric: false },
  { make: 'Genesis', model: 'G70', price: 42500, electric: false },
  { make: 'Volvo', model: 'S60', price: 46500, electric: false },
  { make: 'Porsche', model: '911', price: 115000, electric: false },
  { make: 'Jaguar', model: 'XE', price: 48500, electric: false },
  { make: 'Alfa Romeo', model: 'Giulia', price: 46500, electric: false },
  { make: 'Tesla', model: 'Model X', price: 94950, electric: true },
  { make: 'Ford', model: 'Mustang', price: 35500, electric: false },
  { make: 'Chevrolet', model: 'Corvette', price: 65500, electric: false },
  { make: 'Dodge', model: 'Charger', price: 38500, electric: false },
  { make: 'Toyota', model: 'Camry', price: 31500, electric: false },
  { make: 'Honda', model: 'Accord', price: 30500, electric: false },
  { make: 'Nissan', model: 'Rogue', price: 29500, electric: false },
  { make: 'Hyundai', model: 'Tucson', price: 28500, electric: false },
  { make: 'Kia', model: 'Telluride', price: 39500, electric: false },
  { make: 'Mazda', model: 'Mazda3', price: 27500, electric: false },
  { make: 'Subaru', model: 'Forester', price: 30500, electric: false },
  { make: 'Volkswagen', model: 'Atlas', price: 38500, electric: false },
  { make: 'BMW', model: 'X3', price: 49500, electric: false },
  { make: 'Mercedes-Benz', model: 'GLC', price: 52500, electric: false },
  { make: 'Audi', model: 'Q5', price: 51500, electric: false },
]
